# .air.toml

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -buildvcs=false -o ./tmp/main ./cmd/forum"
  bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["tmp", "build"]
  delay = 1000
  log = "build.log"
  send_interrupt = true

[log]
  time = true

[color]
  main = "yellow"