FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache git

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

RUN go install github.com/air-verse/air@latest

COPY . .

EXPOSE 8080

CMD ["air"]